#!/usr/bin/env python

import os
import argparse

argparser = argparse.ArgumentParser()
argparser.add_argument("-f", "--files", nargs='*' , type=str, default="rules.py", help="rules file(s)")
args = argparser.parse_args()

if __name__ == "__main__":
    FILE_INTERPRETED = "src/rules.py"
    os.system(f"echo > {FILE_INTERPRETED}")
    for file in args.files:
        os.system(f"cat {file} >> {FILE_INTERPRETED}")
    os.system(f"python3 src/main.py")